spring:
  application:
    name: lastsecond
  datasource:
      url: jdbc:postgresql://localhost:5433/doconnect
      port: 5433
      username: postgres
      password: khanhpham2101
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/V1__create_flight_booking_table.xml
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:../config/keystore.p12
    key-store-password: khanhpham2101
    key-store-type: PKCS12
    key-alias: mycert
